version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2
    steps:
      - checkout
      - run:
          name: Pin packages
          command: |
            opam pin add -y -n track_utils .
      - run:
          name: Install system dependencies
          command: opam depext -y track_utils
      - run:
          name: Install OCaml dependencies
          command: opam install --deps-only -y track_utils
      - run:
          name: Build
          command: opam config exec -- make build
      - run:
          name: Test
          command: opam config exec -- make test
      - run:
          name: Build
          command: opam config exec -- make docs
      - store_artifacts:
          path: _build/default/_doc/_html
workflows:
  version: 2
  build:
    jobs:
    - build